worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;

    server {
        listen 80;
        server_name localhost;

        # hknc를 기본 루트로 변경
        root /usr/share/nginx/html/hknc;
        index index.shtml index.html;

        # SSI를 전체에서 활성화
        ssi on;
        ssi_types text/html;
        ssi_silent_errors off;

        location / {
            try_files
                $uri
                $uri.shtml
                $uri.html
                $uri/index.shtml
                $uri/index.html
                =404;
        }
    }

    # server {
    #     listen 443 ssl;
    #     server_name localhost;

    #     ssl_certificate     /etc/nginx/ssl/cert.pem;
    #     ssl_certificate_key /etc/nginx/ssl/key.pem;

    #     root /usr/share/nginx/html;
    #     index index.shtml index.html;

    #     location / {
    #         try_files $uri $uri.shtml $uri.html =404;
    #     }

    #     location ~ \.shtml$ {
    #         ssi on;
    #     }
    # }
}
